from datetime import datetime
from typing import Any, Dict, Optional
from exceptions import ValidationException

class Alert:
    """
    Represents an Alert domain entity in the FinGuard platform.
    Defines flags generated by risky transactions.
    """
    def __init__(
        self,
        alert_id: Optional[int],
        transaction_id: int,
        customer_id: int,
        risk_score: int,
        status: str = "OPEN",
        created_at: Optional[datetime] = None
    ) -> None:
        self.alert_id = alert_id
        self.transaction_id = transaction_id
        self.customer_id = customer_id
        self.risk_score = risk_score
        self.status = status
        self.created_at = created_at or datetime.now()

    def validate(self) -> None:
        """
        Validates alert fields.
        Raises:
            ValidationException: If checks fail.
        """
        if self.transaction_id <= 0:
            raise ValidationException(f"Invalid transaction_id: {self.transaction_id}. Must be positive.")
        if self.customer_id <= 0:
            raise ValidationException(f"Invalid customer_id: {self.customer_id}. Must be positive.")
        if not (0 <= self.risk_score <= 100):
            raise ValidationException(f"Alert risk_score must be between 0 and 100. Got: {self.risk_score}")
        if self.status not in ("OPEN", "UNDER_REVIEW", "RESOLVED_FALSE_POSITIVE", "RESOLVED_TRUE_POSITIVE"):
            raise ValidationException(f"Invalid alert status: '{self.status}'")

    def to_dict(self) -> Dict[str, Any]:
        """
        Serializes the object properties into a dictionary.
        """
        return {
            "alert_id": self.alert_id,
            "transaction_id": self.transaction_id,
            "customer_id": self.customer_id,
            "risk_score": self.risk_score,
            "status": self.status,
            "created_at": self.created_at.isoformat() if isinstance(self.created_at, datetime) else self.created_at,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Alert":
        """
        Deserializes a dictionary into an Alert entity object instance.
        """
        created_at = data.get("created_at")
        if isinstance(created_at, str):
            try:
                created_at = datetime.fromisoformat(created_at)
            except ValueError:
                pass

        return cls(
            alert_id=data.get("alert_id"),
            transaction_id=data.get("transaction_id", 0),
            customer_id=data.get("customer_id", 0),
            risk_score=data.get("risk_score", 0),
            status=data.get("status", "OPEN"),
            created_at=created_at
        )

    def __str__(self) -> str:
        return f"Alert(ID: {self.alert_id}, Tx: {self.transaction_id}, Customer: {self.customer_id}, Risk: {self.risk_score}, Status: {self.status})"
